version: 2.1
jobs:
  build_reverse_proxy:
    working_directory: ~/cd0354-monolith-to-microservices-project/udagram-reverseproxy
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/cd0354-monolith-to-microservices-project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build reverse proxy
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/reverseproxy:$TAG -t $DOCKERHUB_USERNAME/udagram-api-user:latest .
      - run:
          name: Push image to DockerHub
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/reverseproxy:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
  build_frontend:
    working_directory: ~/cd0354-monolith-to-microservices-project/udagram-frontend
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/cd0354-monolith-to-microservices-project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build frontend
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-frontend:$TAG -t $DOCKERHUB_USERNAME/udagram-api-user:latest .
      - run:
          name: Push image to DockerHub
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-frontend:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
  build_feed:
    working_directory: ~/cd0354-monolith-to-microservices-project/udagram-api-feed
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/cd0354-monolith-to-microservices-project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build backend api feed
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-api-feed:$TAG -t $DOCKERHUB_USERNAME/udagram-api-user:latest .
      - run:
          name: Push image to DockerHub
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
  build_user:
    working_directory: ~/cd0354-monolith-to-microservices-project/udagram-api-user
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/cd0354-monolith-to-microservices-project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build backend api user
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-api-user:$TAG -t $DOCKERHUB_USERNAME/udagram-api-user:latest .
      - run:
          name: Push image to DockerHub
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-user:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest             
workflows:
  build:
    jobs:
      - build_reverse_proxy
      - build_frontend
      - build_feed
      - build_user