version: 2.1
jobs:
  build_reverse_proxy:
    working_directory: ~/cd0354-monolith-to-microservices-project/udagram-reverseproxy
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/cd0354-monolith-to-microservices-project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build reverse proxy
          command: |
            TAG=1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG
workflows:
  build:
    jobs:
      - build_reverse_proxy